# Generated by Django 5.0.6 on 2024-05-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='Brand_logo',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
