# Generated by Django 5.0.6 on 2024-05-12 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_brands_brand_logo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='brands',
            new_name='brand',
        ),
    ]
